// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto
#ifndef GRPC_message_2eproto__INCLUDED
#define GRPC_message_2eproto__INCLUDED

#include "message.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace message {

class ResourceService final {
 public:
  static constexpr char const* service_full_name() {
    return "message.ResourceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AddIcon(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::message::AddIconRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::AddIconRsp>> AsyncAddIcon(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::AddIconRsp>>(AsyncAddIconRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::AddIconRsp>> PrepareAsyncAddIcon(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::AddIconRsp>>(PrepareAsyncAddIconRaw(context, request, cq));
    }
    virtual ::grpc::Status GetIcon(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::message::GetIconRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::GetIconRsp>> AsyncGetIcon(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::GetIconRsp>>(AsyncGetIconRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::GetIconRsp>> PrepareAsyncGetIcon(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message::GetIconRsp>>(PrepareAsyncGetIconRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AddIcon(::grpc::ClientContext* context, const ::message::AddIconReq* request, ::message::AddIconRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddIcon(::grpc::ClientContext* context, const ::message::AddIconReq* request, ::message::AddIconRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetIcon(::grpc::ClientContext* context, const ::message::GetIconReq* request, ::message::GetIconRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetIcon(::grpc::ClientContext* context, const ::message::GetIconReq* request, ::message::GetIconRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::AddIconRsp>* AsyncAddIconRaw(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::AddIconRsp>* PrepareAsyncAddIconRaw(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::GetIconRsp>* AsyncGetIconRaw(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message::GetIconRsp>* PrepareAsyncGetIconRaw(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AddIcon(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::message::AddIconRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::AddIconRsp>> AsyncAddIcon(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::AddIconRsp>>(AsyncAddIconRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::AddIconRsp>> PrepareAsyncAddIcon(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::AddIconRsp>>(PrepareAsyncAddIconRaw(context, request, cq));
    }
    ::grpc::Status GetIcon(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::message::GetIconRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::GetIconRsp>> AsyncGetIcon(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::GetIconRsp>>(AsyncGetIconRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::GetIconRsp>> PrepareAsyncGetIcon(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message::GetIconRsp>>(PrepareAsyncGetIconRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AddIcon(::grpc::ClientContext* context, const ::message::AddIconReq* request, ::message::AddIconRsp* response, std::function<void(::grpc::Status)>) override;
      void AddIcon(::grpc::ClientContext* context, const ::message::AddIconReq* request, ::message::AddIconRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetIcon(::grpc::ClientContext* context, const ::message::GetIconReq* request, ::message::GetIconRsp* response, std::function<void(::grpc::Status)>) override;
      void GetIcon(::grpc::ClientContext* context, const ::message::GetIconReq* request, ::message::GetIconRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::message::AddIconRsp>* AsyncAddIconRaw(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message::AddIconRsp>* PrepareAsyncAddIconRaw(::grpc::ClientContext* context, const ::message::AddIconReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message::GetIconRsp>* AsyncGetIconRaw(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message::GetIconRsp>* PrepareAsyncGetIconRaw(::grpc::ClientContext* context, const ::message::GetIconReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddIcon_;
    const ::grpc::internal::RpcMethod rpcmethod_GetIcon_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AddIcon(::grpc::ServerContext* context, const ::message::AddIconReq* request, ::message::AddIconRsp* response);
    virtual ::grpc::Status GetIcon(::grpc::ServerContext* context, const ::message::GetIconReq* request, ::message::GetIconRsp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddIcon() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddIcon(::grpc::ServerContext* /*context*/, const ::message::AddIconReq* /*request*/, ::message::AddIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddIcon(::grpc::ServerContext* context, ::message::AddIconReq* request, ::grpc::ServerAsyncResponseWriter< ::message::AddIconRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetIcon() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIcon(::grpc::ServerContext* /*context*/, const ::message::GetIconReq* /*request*/, ::message::GetIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetIcon(::grpc::ServerContext* context, ::message::GetIconReq* request, ::grpc::ServerAsyncResponseWriter< ::message::GetIconRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddIcon<WithAsyncMethod_GetIcon<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AddIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddIcon() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::message::AddIconReq, ::message::AddIconRsp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::message::AddIconReq* request, ::message::AddIconRsp* response) { return this->AddIcon(context, request, response); }));}
    void SetMessageAllocatorFor_AddIcon(
        ::grpc::MessageAllocator< ::message::AddIconReq, ::message::AddIconRsp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::message::AddIconReq, ::message::AddIconRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddIcon(::grpc::ServerContext* /*context*/, const ::message::AddIconReq* /*request*/, ::message::AddIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddIcon(
      ::grpc::CallbackServerContext* /*context*/, const ::message::AddIconReq* /*request*/, ::message::AddIconRsp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetIcon() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::message::GetIconReq, ::message::GetIconRsp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::message::GetIconReq* request, ::message::GetIconRsp* response) { return this->GetIcon(context, request, response); }));}
    void SetMessageAllocatorFor_GetIcon(
        ::grpc::MessageAllocator< ::message::GetIconReq, ::message::GetIconRsp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::message::GetIconReq, ::message::GetIconRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIcon(::grpc::ServerContext* /*context*/, const ::message::GetIconReq* /*request*/, ::message::GetIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetIcon(
      ::grpc::CallbackServerContext* /*context*/, const ::message::GetIconReq* /*request*/, ::message::GetIconRsp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AddIcon<WithCallbackMethod_GetIcon<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddIcon() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddIcon(::grpc::ServerContext* /*context*/, const ::message::AddIconReq* /*request*/, ::message::AddIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetIcon() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIcon(::grpc::ServerContext* /*context*/, const ::message::GetIconReq* /*request*/, ::message::GetIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddIcon() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddIcon(::grpc::ServerContext* /*context*/, const ::message::AddIconReq* /*request*/, ::message::AddIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddIcon(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetIcon() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIcon(::grpc::ServerContext* /*context*/, const ::message::GetIconReq* /*request*/, ::message::GetIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetIcon(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddIcon() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddIcon(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddIcon(::grpc::ServerContext* /*context*/, const ::message::AddIconReq* /*request*/, ::message::AddIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddIcon(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetIcon() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetIcon(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIcon(::grpc::ServerContext* /*context*/, const ::message::GetIconReq* /*request*/, ::message::GetIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetIcon(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddIcon() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::message::AddIconReq, ::message::AddIconRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::message::AddIconReq, ::message::AddIconRsp>* streamer) {
                       return this->StreamedAddIcon(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddIcon(::grpc::ServerContext* /*context*/, const ::message::AddIconReq* /*request*/, ::message::AddIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddIcon(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::message::AddIconReq,::message::AddIconRsp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetIcon : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetIcon() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::message::GetIconReq, ::message::GetIconRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::message::GetIconReq, ::message::GetIconRsp>* streamer) {
                       return this->StreamedGetIcon(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetIcon() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetIcon(::grpc::ServerContext* /*context*/, const ::message::GetIconReq* /*request*/, ::message::GetIconRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetIcon(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::message::GetIconReq,::message::GetIconRsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddIcon<WithStreamedUnaryMethod_GetIcon<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddIcon<WithStreamedUnaryMethod_GetIcon<Service > > StreamedService;
};

}  // namespace message


#endif  // GRPC_message_2eproto__INCLUDED
