// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#include "message.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace message {

inline constexpr ReplyAddFriendRsp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_{0},
        replyuid_{0},
        touid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReplyAddFriendRsp::ReplyAddFriendRsp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReplyAddFriendRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReplyAddFriendRspDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReplyAddFriendRspDefaultTypeInternal() {}
  union {
    ReplyAddFriendRsp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReplyAddFriendRspDefaultTypeInternal _ReplyAddFriendRsp_default_instance_;

inline constexpr ReplyAddFriendReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : reply_stat_{0},
        reply_uid_{0},
        to_uid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReplyAddFriendReq::ReplyAddFriendReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReplyAddFriendReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReplyAddFriendReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReplyAddFriendReqDefaultTypeInternal() {}
  union {
    ReplyAddFriendReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReplyAddFriendReqDefaultTypeInternal _ReplyAddFriendReq_default_instance_;

inline constexpr LoginRsp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LoginRsp::LoginRsp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LoginRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginRspDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginRspDefaultTypeInternal() {}
  union {
    LoginRsp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginRspDefaultTypeInternal _LoginRsp_default_instance_;

inline constexpr LoginReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LoginReq::LoginReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LoginReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginReqDefaultTypeInternal() {}
  union {
    LoginReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginReqDefaultTypeInternal _LoginReq_default_instance_;

inline constexpr GetIconRsp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : icon_pixmap_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetIconRsp::GetIconRsp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetIconRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetIconRspDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetIconRspDefaultTypeInternal() {}
  union {
    GetIconRsp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetIconRspDefaultTypeInternal _GetIconRsp_default_instance_;

inline constexpr GetIconReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : url_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetIconReq::GetIconReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetIconReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetIconReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetIconReqDefaultTypeInternal() {}
  union {
    GetIconReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetIconReqDefaultTypeInternal _GetIconReq_default_instance_;

inline constexpr AddIconRsp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : url_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddIconRsp::AddIconRsp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AddIconRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddIconRspDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddIconRspDefaultTypeInternal() {}
  union {
    AddIconRsp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddIconRspDefaultTypeInternal _AddIconRsp_default_instance_;

inline constexpr AddIconReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : contents_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddIconReq::AddIconReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AddIconReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddIconReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddIconReqDefaultTypeInternal() {}
  union {
    AddIconReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddIconReqDefaultTypeInternal _AddIconReq_default_instance_;

inline constexpr AddFriendRsp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_{0},
        fromuid_{0},
        destuid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddFriendRsp::AddFriendRsp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AddFriendRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddFriendRspDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddFriendRspDefaultTypeInternal() {}
  union {
    AddFriendRsp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddFriendRspDefaultTypeInternal _AddFriendRsp_default_instance_;

inline constexpr AddFriendReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : fromname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        desc_msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fromnick_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fromicon_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fromuid_{0},
        destuid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddFriendReq::AddFriendReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AddFriendReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddFriendReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddFriendReqDefaultTypeInternal() {}
  union {
    AddFriendReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddFriendReqDefaultTypeInternal _AddFriendReq_default_instance_;
}  // namespace message
static ::_pb::Metadata file_level_metadata_message_2eproto[10];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_message_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_message_2eproto = nullptr;
const ::uint32_t TableStruct_message_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::LoginReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::LoginReq, _impl_.uid_),
    PROTOBUF_FIELD_OFFSET(::message::LoginReq, _impl_.token_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::LoginRsp, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::LoginRsp, _impl_.error_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::AddFriendReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::AddFriendReq, _impl_.fromuid_),
    PROTOBUF_FIELD_OFFSET(::message::AddFriendReq, _impl_.fromname_),
    PROTOBUF_FIELD_OFFSET(::message::AddFriendReq, _impl_.destuid_),
    PROTOBUF_FIELD_OFFSET(::message::AddFriendReq, _impl_.desc_msg_),
    PROTOBUF_FIELD_OFFSET(::message::AddFriendReq, _impl_.fromnick_),
    PROTOBUF_FIELD_OFFSET(::message::AddFriendReq, _impl_.fromicon_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::AddFriendRsp, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::AddFriendRsp, _impl_.error_),
    PROTOBUF_FIELD_OFFSET(::message::AddFriendRsp, _impl_.fromuid_),
    PROTOBUF_FIELD_OFFSET(::message::AddFriendRsp, _impl_.destuid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::ReplyAddFriendReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::ReplyAddFriendReq, _impl_.reply_stat_),
    PROTOBUF_FIELD_OFFSET(::message::ReplyAddFriendReq, _impl_.reply_uid_),
    PROTOBUF_FIELD_OFFSET(::message::ReplyAddFriendReq, _impl_.to_uid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::ReplyAddFriendRsp, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::ReplyAddFriendRsp, _impl_.error_),
    PROTOBUF_FIELD_OFFSET(::message::ReplyAddFriendRsp, _impl_.replyuid_),
    PROTOBUF_FIELD_OFFSET(::message::ReplyAddFriendRsp, _impl_.touid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::AddIconReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::AddIconReq, _impl_.uid_),
    PROTOBUF_FIELD_OFFSET(::message::AddIconReq, _impl_.contents_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::AddIconRsp, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::AddIconRsp, _impl_.error_),
    PROTOBUF_FIELD_OFFSET(::message::AddIconRsp, _impl_.url_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::GetIconReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::GetIconReq, _impl_.url_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::message::GetIconRsp, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::message::GetIconRsp, _impl_.error_),
    PROTOBUF_FIELD_OFFSET(::message::GetIconRsp, _impl_.icon_pixmap_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::message::LoginReq)},
        {10, -1, -1, sizeof(::message::LoginRsp)},
        {19, -1, -1, sizeof(::message::AddFriendReq)},
        {33, -1, -1, sizeof(::message::AddFriendRsp)},
        {44, -1, -1, sizeof(::message::ReplyAddFriendReq)},
        {55, -1, -1, sizeof(::message::ReplyAddFriendRsp)},
        {66, -1, -1, sizeof(::message::AddIconReq)},
        {76, -1, -1, sizeof(::message::AddIconRsp)},
        {86, -1, -1, sizeof(::message::GetIconReq)},
        {95, -1, -1, sizeof(::message::GetIconRsp)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::message::_LoginReq_default_instance_._instance,
    &::message::_LoginRsp_default_instance_._instance,
    &::message::_AddFriendReq_default_instance_._instance,
    &::message::_AddFriendRsp_default_instance_._instance,
    &::message::_ReplyAddFriendReq_default_instance_._instance,
    &::message::_ReplyAddFriendRsp_default_instance_._instance,
    &::message::_AddIconReq_default_instance_._instance,
    &::message::_AddIconRsp_default_instance_._instance,
    &::message::_GetIconReq_default_instance_._instance,
    &::message::_GetIconRsp_default_instance_._instance,
};
const char descriptor_table_protodef_message_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rmessage.proto\022\007message\"&\n\010LoginReq\022\013\n\003"
    "uid\030\001 \001(\005\022\r\n\005token\030\002 \001(\t\"\031\n\010LoginRsp\022\r\n\005"
    "error\030\001 \001(\005\"x\n\014AddFriendReq\022\017\n\007fromuid\030\001"
    " \001(\005\022\020\n\010fromname\030\002 \001(\t\022\017\n\007destuid\030\003 \001(\005\022"
    "\020\n\010desc_msg\030\004 \001(\t\022\020\n\010fromnick\030\005 \001(\t\022\020\n\010f"
    "romicon\030\006 \001(\t\"\?\n\014AddFriendRsp\022\r\n\005error\030\001"
    " \001(\005\022\017\n\007fromuid\030\002 \001(\005\022\017\n\007destuid\030\003 \001(\005\"J"
    "\n\021ReplyAddFriendReq\022\022\n\nreply_stat\030\001 \001(\005\022"
    "\021\n\treply_uid\030\002 \001(\005\022\016\n\006to_uid\030\003 \001(\005\"C\n\021Re"
    "plyAddFriendRsp\022\r\n\005error\030\001 \001(\005\022\020\n\010replyu"
    "id\030\002 \001(\005\022\r\n\005touid\030\003 \001(\005\"+\n\nAddIconReq\022\013\n"
    "\003uid\030\001 \001(\005\022\020\n\010contents\030\002 \001(\014\"(\n\nAddIconR"
    "sp\022\r\n\005error\030\001 \001(\005\022\013\n\003url\030\002 \001(\t\"\031\n\nGetIco"
    "nReq\022\013\n\003url\030\001 \001(\t\"0\n\nGetIconRsp\022\r\n\005error"
    "\030\001 \001(\005\022\023\n\013icon_pixmap\030\002 \001(\0142@\n\rStatusSer"
    "vice\022/\n\005Login\022\021.message.LoginReq\032\021.messa"
    "ge.LoginRsp\"\0002\226\001\n\013ChatService\022;\n\tAddFrie"
    "nd\022\025.message.AddFriendReq\032\025.message.AddF"
    "riendRsp\"\000\022J\n\016ReplyAddFriend\022\032.message.R"
    "eplyAddFriendReq\032\032.message.ReplyAddFrien"
    "dRsp\"\0002\177\n\017ResourceService\0225\n\007AddIcon\022\023.m"
    "essage.AddIconReq\032\023.message.AddIconRsp\"\000"
    "\0225\n\007GetIcon\022\023.message.GetIconReq\032\023.messa"
    "ge.GetIconRsp\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_message_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_message_2eproto = {
    false,
    false,
    943,
    descriptor_table_protodef_message_2eproto,
    "message.proto",
    &descriptor_table_message_2eproto_once,
    nullptr,
    0,
    10,
    schemas,
    file_default_instances,
    TableStruct_message_2eproto::offsets,
    file_level_metadata_message_2eproto,
    file_level_enum_descriptors_message_2eproto,
    file_level_service_descriptors_message_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_message_2eproto_getter() {
  return &descriptor_table_message_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_message_2eproto(&descriptor_table_message_2eproto);
namespace message {
// ===================================================================

class LoginReq::_Internal {
 public:
};

LoginReq::LoginReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.LoginReq)
}
inline PROTOBUF_NDEBUG_INLINE LoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : token_(arena, from.token_),
        _cached_size_{0} {}

LoginReq::LoginReq(
    ::google::protobuf::Arena* arena,
    const LoginReq& from)
    : ::google::protobuf::Message(arena) {
  LoginReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.uid_ = from._impl_.uid_;

  // @@protoc_insertion_point(copy_constructor:message.LoginReq)
}
inline PROTOBUF_NDEBUG_INLINE LoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void LoginReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.uid_ = {};
}
LoginReq::~LoginReq() {
  // @@protoc_insertion_point(destructor:message.LoginReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LoginReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.token_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:message.LoginReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.uid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LoginReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2> LoginReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LoginReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(LoginReq, _impl_.token_)}},
    // int32 uid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LoginReq, _impl_.uid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LoginReq, _impl_.uid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 uid = 1;
    {PROTOBUF_FIELD_OFFSET(LoginReq, _impl_.uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string token = 2;
    {PROTOBUF_FIELD_OFFSET(LoginReq, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\0\5\0\0\0\0\0"
    "message.LoginReq"
    "token"
  }},
};

::uint8_t* LoginReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.LoginReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 uid = 1;
  if (this->_internal_uid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_uid(), target);
  }

  // string token = 2;
  if (!this->_internal_token().empty()) {
    const std::string& _s = this->_internal_token();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.LoginReq.token");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.LoginReq)
  return target;
}

::size_t LoginReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.LoginReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string token = 2;
  if (!this->_internal_token().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_token());
  }

  // int32 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_uid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LoginReq::_class_data_ = {
    LoginReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LoginReq::GetClassData() const {
  return &_class_data_;
}

void LoginReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LoginReq*>(&to_msg);
  auto& from = static_cast<const LoginReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.LoginReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoginReq::CopyFrom(const LoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.LoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LoginReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LoginReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LoginReq::InternalSwap(LoginReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
        swap(_impl_.uid_, other->_impl_.uid_);
}

::google::protobuf::Metadata LoginReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[0]);
}
// ===================================================================

class LoginRsp::_Internal {
 public:
};

LoginRsp::LoginRsp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.LoginRsp)
}
LoginRsp::LoginRsp(
    ::google::protobuf::Arena* arena, const LoginRsp& from)
    : LoginRsp(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LoginRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LoginRsp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_ = {};
}
LoginRsp::~LoginRsp() {
  // @@protoc_insertion_point(destructor:message.LoginRsp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LoginRsp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LoginRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:message.LoginRsp)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LoginRsp::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> LoginRsp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LoginRsp_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LoginRsp, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LoginRsp, _impl_.error_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(LoginRsp, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* LoginRsp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.LoginRsp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_error(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.LoginRsp)
  return target;
}

::size_t LoginRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.LoginRsp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LoginRsp::_class_data_ = {
    LoginRsp::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LoginRsp::GetClassData() const {
  return &_class_data_;
}

void LoginRsp::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LoginRsp*>(&to_msg);
  auto& from = static_cast<const LoginRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.LoginRsp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoginRsp::CopyFrom(const LoginRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.LoginRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LoginRsp::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LoginRsp::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LoginRsp::InternalSwap(LoginRsp* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.error_, other->_impl_.error_);
}

::google::protobuf::Metadata LoginRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[1]);
}
// ===================================================================

class AddFriendReq::_Internal {
 public:
};

AddFriendReq::AddFriendReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.AddFriendReq)
}
inline PROTOBUF_NDEBUG_INLINE AddFriendReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : fromname_(arena, from.fromname_),
        desc_msg_(arena, from.desc_msg_),
        fromnick_(arena, from.fromnick_),
        fromicon_(arena, from.fromicon_),
        _cached_size_{0} {}

AddFriendReq::AddFriendReq(
    ::google::protobuf::Arena* arena,
    const AddFriendReq& from)
    : ::google::protobuf::Message(arena) {
  AddFriendReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, fromuid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, fromuid_),
           offsetof(Impl_, destuid_) -
               offsetof(Impl_, fromuid_) +
               sizeof(Impl_::destuid_));

  // @@protoc_insertion_point(copy_constructor:message.AddFriendReq)
}
inline PROTOBUF_NDEBUG_INLINE AddFriendReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : fromname_(arena),
        desc_msg_(arena),
        fromnick_(arena),
        fromicon_(arena),
        _cached_size_{0} {}

inline void AddFriendReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, fromuid_),
           0,
           offsetof(Impl_, destuid_) -
               offsetof(Impl_, fromuid_) +
               sizeof(Impl_::destuid_));
}
AddFriendReq::~AddFriendReq() {
  // @@protoc_insertion_point(destructor:message.AddFriendReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AddFriendReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.fromname_.Destroy();
  _impl_.desc_msg_.Destroy();
  _impl_.fromnick_.Destroy();
  _impl_.fromicon_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AddFriendReq::Clear() {
// @@protoc_insertion_point(message_clear_start:message.AddFriendReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fromname_.ClearToEmpty();
  _impl_.desc_msg_.ClearToEmpty();
  _impl_.fromnick_.ClearToEmpty();
  _impl_.fromicon_.ClearToEmpty();
  ::memset(&_impl_.fromuid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.destuid_) -
      reinterpret_cast<char*>(&_impl_.fromuid_)) + sizeof(_impl_.destuid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AddFriendReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 61, 2> AddFriendReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AddFriendReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 fromuid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddFriendReq, _impl_.fromuid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromuid_)}},
    // string fromname = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromname_)}},
    // int32 destuid = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddFriendReq, _impl_.destuid_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.destuid_)}},
    // string desc_msg = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.desc_msg_)}},
    // string fromnick = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromnick_)}},
    // string fromicon = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromicon_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 fromuid = 1;
    {PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string fromname = 2;
    {PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 destuid = 3;
    {PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.destuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string desc_msg = 4;
    {PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.desc_msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string fromnick = 5;
    {PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromnick_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string fromicon = 6;
    {PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromicon_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\0\10\0\10\10\10\0"
    "message.AddFriendReq"
    "fromname"
    "desc_msg"
    "fromnick"
    "fromicon"
  }},
};

::uint8_t* AddFriendReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.AddFriendReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 fromuid = 1;
  if (this->_internal_fromuid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_fromuid(), target);
  }

  // string fromname = 2;
  if (!this->_internal_fromname().empty()) {
    const std::string& _s = this->_internal_fromname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.AddFriendReq.fromname");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int32 destuid = 3;
  if (this->_internal_destuid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_destuid(), target);
  }

  // string desc_msg = 4;
  if (!this->_internal_desc_msg().empty()) {
    const std::string& _s = this->_internal_desc_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.AddFriendReq.desc_msg");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string fromnick = 5;
  if (!this->_internal_fromnick().empty()) {
    const std::string& _s = this->_internal_fromnick();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.AddFriendReq.fromnick");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // string fromicon = 6;
  if (!this->_internal_fromicon().empty()) {
    const std::string& _s = this->_internal_fromicon();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.AddFriendReq.fromicon");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.AddFriendReq)
  return target;
}

::size_t AddFriendReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.AddFriendReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string fromname = 2;
  if (!this->_internal_fromname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_fromname());
  }

  // string desc_msg = 4;
  if (!this->_internal_desc_msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_desc_msg());
  }

  // string fromnick = 5;
  if (!this->_internal_fromnick().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_fromnick());
  }

  // string fromicon = 6;
  if (!this->_internal_fromicon().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_fromicon());
  }

  // int32 fromuid = 1;
  if (this->_internal_fromuid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_fromuid());
  }

  // int32 destuid = 3;
  if (this->_internal_destuid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_destuid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AddFriendReq::_class_data_ = {
    AddFriendReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AddFriendReq::GetClassData() const {
  return &_class_data_;
}

void AddFriendReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AddFriendReq*>(&to_msg);
  auto& from = static_cast<const AddFriendReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.AddFriendReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_fromname().empty()) {
    _this->_internal_set_fromname(from._internal_fromname());
  }
  if (!from._internal_desc_msg().empty()) {
    _this->_internal_set_desc_msg(from._internal_desc_msg());
  }
  if (!from._internal_fromnick().empty()) {
    _this->_internal_set_fromnick(from._internal_fromnick());
  }
  if (!from._internal_fromicon().empty()) {
    _this->_internal_set_fromicon(from._internal_fromicon());
  }
  if (from._internal_fromuid() != 0) {
    _this->_internal_set_fromuid(from._internal_fromuid());
  }
  if (from._internal_destuid() != 0) {
    _this->_internal_set_destuid(from._internal_destuid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddFriendReq::CopyFrom(const AddFriendReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.AddFriendReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AddFriendReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AddFriendReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AddFriendReq::InternalSwap(AddFriendReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fromname_, &other->_impl_.fromname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_msg_, &other->_impl_.desc_msg_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fromnick_, &other->_impl_.fromnick_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fromicon_, &other->_impl_.fromicon_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.destuid_)
      + sizeof(AddFriendReq::_impl_.destuid_)
      - PROTOBUF_FIELD_OFFSET(AddFriendReq, _impl_.fromuid_)>(
          reinterpret_cast<char*>(&_impl_.fromuid_),
          reinterpret_cast<char*>(&other->_impl_.fromuid_));
}

::google::protobuf::Metadata AddFriendReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[2]);
}
// ===================================================================

class AddFriendRsp::_Internal {
 public:
};

AddFriendRsp::AddFriendRsp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.AddFriendRsp)
}
AddFriendRsp::AddFriendRsp(
    ::google::protobuf::Arena* arena, const AddFriendRsp& from)
    : AddFriendRsp(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AddFriendRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AddFriendRsp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, error_),
           0,
           offsetof(Impl_, destuid_) -
               offsetof(Impl_, error_) +
               sizeof(Impl_::destuid_));
}
AddFriendRsp::~AddFriendRsp() {
  // @@protoc_insertion_point(destructor:message.AddFriendRsp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AddFriendRsp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AddFriendRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:message.AddFriendRsp)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.error_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.destuid_) -
      reinterpret_cast<char*>(&_impl_.error_)) + sizeof(_impl_.destuid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AddFriendRsp::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> AddFriendRsp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AddFriendRsp_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddFriendRsp, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendRsp, _impl_.error_)}},
    // int32 fromuid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddFriendRsp, _impl_.fromuid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendRsp, _impl_.fromuid_)}},
    // int32 destuid = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddFriendRsp, _impl_.destuid_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(AddFriendRsp, _impl_.destuid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(AddFriendRsp, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 fromuid = 2;
    {PROTOBUF_FIELD_OFFSET(AddFriendRsp, _impl_.fromuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 destuid = 3;
    {PROTOBUF_FIELD_OFFSET(AddFriendRsp, _impl_.destuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* AddFriendRsp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.AddFriendRsp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_error(), target);
  }

  // int32 fromuid = 2;
  if (this->_internal_fromuid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_fromuid(), target);
  }

  // int32 destuid = 3;
  if (this->_internal_destuid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_destuid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.AddFriendRsp)
  return target;
}

::size_t AddFriendRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.AddFriendRsp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_error());
  }

  // int32 fromuid = 2;
  if (this->_internal_fromuid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_fromuid());
  }

  // int32 destuid = 3;
  if (this->_internal_destuid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_destuid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AddFriendRsp::_class_data_ = {
    AddFriendRsp::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AddFriendRsp::GetClassData() const {
  return &_class_data_;
}

void AddFriendRsp::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AddFriendRsp*>(&to_msg);
  auto& from = static_cast<const AddFriendRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.AddFriendRsp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_fromuid() != 0) {
    _this->_internal_set_fromuid(from._internal_fromuid());
  }
  if (from._internal_destuid() != 0) {
    _this->_internal_set_destuid(from._internal_destuid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddFriendRsp::CopyFrom(const AddFriendRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.AddFriendRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AddFriendRsp::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AddFriendRsp::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AddFriendRsp::InternalSwap(AddFriendRsp* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AddFriendRsp, _impl_.destuid_)
      + sizeof(AddFriendRsp::_impl_.destuid_)
      - PROTOBUF_FIELD_OFFSET(AddFriendRsp, _impl_.error_)>(
          reinterpret_cast<char*>(&_impl_.error_),
          reinterpret_cast<char*>(&other->_impl_.error_));
}

::google::protobuf::Metadata AddFriendRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[3]);
}
// ===================================================================

class ReplyAddFriendReq::_Internal {
 public:
};

ReplyAddFriendReq::ReplyAddFriendReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.ReplyAddFriendReq)
}
ReplyAddFriendReq::ReplyAddFriendReq(
    ::google::protobuf::Arena* arena, const ReplyAddFriendReq& from)
    : ReplyAddFriendReq(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ReplyAddFriendReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ReplyAddFriendReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, reply_stat_),
           0,
           offsetof(Impl_, to_uid_) -
               offsetof(Impl_, reply_stat_) +
               sizeof(Impl_::to_uid_));
}
ReplyAddFriendReq::~ReplyAddFriendReq() {
  // @@protoc_insertion_point(destructor:message.ReplyAddFriendReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ReplyAddFriendReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ReplyAddFriendReq::Clear() {
// @@protoc_insertion_point(message_clear_start:message.ReplyAddFriendReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.reply_stat_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.to_uid_) -
      reinterpret_cast<char*>(&_impl_.reply_stat_)) + sizeof(_impl_.to_uid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ReplyAddFriendReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ReplyAddFriendReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ReplyAddFriendReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 reply_stat = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReplyAddFriendReq, _impl_.reply_stat_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ReplyAddFriendReq, _impl_.reply_stat_)}},
    // int32 reply_uid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReplyAddFriendReq, _impl_.reply_uid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ReplyAddFriendReq, _impl_.reply_uid_)}},
    // int32 to_uid = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReplyAddFriendReq, _impl_.to_uid_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ReplyAddFriendReq, _impl_.to_uid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 reply_stat = 1;
    {PROTOBUF_FIELD_OFFSET(ReplyAddFriendReq, _impl_.reply_stat_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 reply_uid = 2;
    {PROTOBUF_FIELD_OFFSET(ReplyAddFriendReq, _impl_.reply_uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 to_uid = 3;
    {PROTOBUF_FIELD_OFFSET(ReplyAddFriendReq, _impl_.to_uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ReplyAddFriendReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.ReplyAddFriendReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 reply_stat = 1;
  if (this->_internal_reply_stat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_reply_stat(), target);
  }

  // int32 reply_uid = 2;
  if (this->_internal_reply_uid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_reply_uid(), target);
  }

  // int32 to_uid = 3;
  if (this->_internal_to_uid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_to_uid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.ReplyAddFriendReq)
  return target;
}

::size_t ReplyAddFriendReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.ReplyAddFriendReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 reply_stat = 1;
  if (this->_internal_reply_stat() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_reply_stat());
  }

  // int32 reply_uid = 2;
  if (this->_internal_reply_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_reply_uid());
  }

  // int32 to_uid = 3;
  if (this->_internal_to_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_to_uid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ReplyAddFriendReq::_class_data_ = {
    ReplyAddFriendReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ReplyAddFriendReq::GetClassData() const {
  return &_class_data_;
}

void ReplyAddFriendReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ReplyAddFriendReq*>(&to_msg);
  auto& from = static_cast<const ReplyAddFriendReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.ReplyAddFriendReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_reply_stat() != 0) {
    _this->_internal_set_reply_stat(from._internal_reply_stat());
  }
  if (from._internal_reply_uid() != 0) {
    _this->_internal_set_reply_uid(from._internal_reply_uid());
  }
  if (from._internal_to_uid() != 0) {
    _this->_internal_set_to_uid(from._internal_to_uid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReplyAddFriendReq::CopyFrom(const ReplyAddFriendReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.ReplyAddFriendReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ReplyAddFriendReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ReplyAddFriendReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ReplyAddFriendReq::InternalSwap(ReplyAddFriendReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReplyAddFriendReq, _impl_.to_uid_)
      + sizeof(ReplyAddFriendReq::_impl_.to_uid_)
      - PROTOBUF_FIELD_OFFSET(ReplyAddFriendReq, _impl_.reply_stat_)>(
          reinterpret_cast<char*>(&_impl_.reply_stat_),
          reinterpret_cast<char*>(&other->_impl_.reply_stat_));
}

::google::protobuf::Metadata ReplyAddFriendReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[4]);
}
// ===================================================================

class ReplyAddFriendRsp::_Internal {
 public:
};

ReplyAddFriendRsp::ReplyAddFriendRsp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.ReplyAddFriendRsp)
}
ReplyAddFriendRsp::ReplyAddFriendRsp(
    ::google::protobuf::Arena* arena, const ReplyAddFriendRsp& from)
    : ReplyAddFriendRsp(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ReplyAddFriendRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ReplyAddFriendRsp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, error_),
           0,
           offsetof(Impl_, touid_) -
               offsetof(Impl_, error_) +
               sizeof(Impl_::touid_));
}
ReplyAddFriendRsp::~ReplyAddFriendRsp() {
  // @@protoc_insertion_point(destructor:message.ReplyAddFriendRsp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ReplyAddFriendRsp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ReplyAddFriendRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:message.ReplyAddFriendRsp)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.error_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.touid_) -
      reinterpret_cast<char*>(&_impl_.error_)) + sizeof(_impl_.touid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ReplyAddFriendRsp::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ReplyAddFriendRsp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ReplyAddFriendRsp_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReplyAddFriendRsp, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ReplyAddFriendRsp, _impl_.error_)}},
    // int32 replyuid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReplyAddFriendRsp, _impl_.replyuid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ReplyAddFriendRsp, _impl_.replyuid_)}},
    // int32 touid = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReplyAddFriendRsp, _impl_.touid_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ReplyAddFriendRsp, _impl_.touid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(ReplyAddFriendRsp, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 replyuid = 2;
    {PROTOBUF_FIELD_OFFSET(ReplyAddFriendRsp, _impl_.replyuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 touid = 3;
    {PROTOBUF_FIELD_OFFSET(ReplyAddFriendRsp, _impl_.touid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ReplyAddFriendRsp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.ReplyAddFriendRsp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_error(), target);
  }

  // int32 replyuid = 2;
  if (this->_internal_replyuid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_replyuid(), target);
  }

  // int32 touid = 3;
  if (this->_internal_touid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_touid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.ReplyAddFriendRsp)
  return target;
}

::size_t ReplyAddFriendRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.ReplyAddFriendRsp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_error());
  }

  // int32 replyuid = 2;
  if (this->_internal_replyuid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_replyuid());
  }

  // int32 touid = 3;
  if (this->_internal_touid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_touid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ReplyAddFriendRsp::_class_data_ = {
    ReplyAddFriendRsp::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ReplyAddFriendRsp::GetClassData() const {
  return &_class_data_;
}

void ReplyAddFriendRsp::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ReplyAddFriendRsp*>(&to_msg);
  auto& from = static_cast<const ReplyAddFriendRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.ReplyAddFriendRsp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_replyuid() != 0) {
    _this->_internal_set_replyuid(from._internal_replyuid());
  }
  if (from._internal_touid() != 0) {
    _this->_internal_set_touid(from._internal_touid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReplyAddFriendRsp::CopyFrom(const ReplyAddFriendRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.ReplyAddFriendRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ReplyAddFriendRsp::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ReplyAddFriendRsp::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ReplyAddFriendRsp::InternalSwap(ReplyAddFriendRsp* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReplyAddFriendRsp, _impl_.touid_)
      + sizeof(ReplyAddFriendRsp::_impl_.touid_)
      - PROTOBUF_FIELD_OFFSET(ReplyAddFriendRsp, _impl_.error_)>(
          reinterpret_cast<char*>(&_impl_.error_),
          reinterpret_cast<char*>(&other->_impl_.error_));
}

::google::protobuf::Metadata ReplyAddFriendRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[5]);
}
// ===================================================================

class AddIconReq::_Internal {
 public:
};

AddIconReq::AddIconReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.AddIconReq)
}
inline PROTOBUF_NDEBUG_INLINE AddIconReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : contents_(arena, from.contents_),
        _cached_size_{0} {}

AddIconReq::AddIconReq(
    ::google::protobuf::Arena* arena,
    const AddIconReq& from)
    : ::google::protobuf::Message(arena) {
  AddIconReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.uid_ = from._impl_.uid_;

  // @@protoc_insertion_point(copy_constructor:message.AddIconReq)
}
inline PROTOBUF_NDEBUG_INLINE AddIconReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : contents_(arena),
        _cached_size_{0} {}

inline void AddIconReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.uid_ = {};
}
AddIconReq::~AddIconReq() {
  // @@protoc_insertion_point(destructor:message.AddIconReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AddIconReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.contents_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AddIconReq::Clear() {
// @@protoc_insertion_point(message_clear_start:message.AddIconReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.contents_.ClearToEmpty();
  _impl_.uid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AddIconReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> AddIconReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AddIconReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes contents = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AddIconReq, _impl_.contents_)}},
    // int32 uid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddIconReq, _impl_.uid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AddIconReq, _impl_.uid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 uid = 1;
    {PROTOBUF_FIELD_OFFSET(AddIconReq, _impl_.uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bytes contents = 2;
    {PROTOBUF_FIELD_OFFSET(AddIconReq, _impl_.contents_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* AddIconReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.AddIconReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 uid = 1;
  if (this->_internal_uid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_uid(), target);
  }

  // bytes contents = 2;
  if (!this->_internal_contents().empty()) {
    const std::string& _s = this->_internal_contents();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.AddIconReq)
  return target;
}

::size_t AddIconReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.AddIconReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes contents = 2;
  if (!this->_internal_contents().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_contents());
  }

  // int32 uid = 1;
  if (this->_internal_uid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_uid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AddIconReq::_class_data_ = {
    AddIconReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AddIconReq::GetClassData() const {
  return &_class_data_;
}

void AddIconReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AddIconReq*>(&to_msg);
  auto& from = static_cast<const AddIconReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.AddIconReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_contents().empty()) {
    _this->_internal_set_contents(from._internal_contents());
  }
  if (from._internal_uid() != 0) {
    _this->_internal_set_uid(from._internal_uid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddIconReq::CopyFrom(const AddIconReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.AddIconReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AddIconReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AddIconReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AddIconReq::InternalSwap(AddIconReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.contents_, &other->_impl_.contents_, arena);
        swap(_impl_.uid_, other->_impl_.uid_);
}

::google::protobuf::Metadata AddIconReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[6]);
}
// ===================================================================

class AddIconRsp::_Internal {
 public:
};

AddIconRsp::AddIconRsp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.AddIconRsp)
}
inline PROTOBUF_NDEBUG_INLINE AddIconRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : url_(arena, from.url_),
        _cached_size_{0} {}

AddIconRsp::AddIconRsp(
    ::google::protobuf::Arena* arena,
    const AddIconRsp& from)
    : ::google::protobuf::Message(arena) {
  AddIconRsp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.error_ = from._impl_.error_;

  // @@protoc_insertion_point(copy_constructor:message.AddIconRsp)
}
inline PROTOBUF_NDEBUG_INLINE AddIconRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : url_(arena),
        _cached_size_{0} {}

inline void AddIconRsp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_ = {};
}
AddIconRsp::~AddIconRsp() {
  // @@protoc_insertion_point(destructor:message.AddIconRsp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AddIconRsp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.url_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AddIconRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:message.AddIconRsp)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.url_.ClearToEmpty();
  _impl_.error_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AddIconRsp::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2> AddIconRsp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AddIconRsp_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string url = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AddIconRsp, _impl_.url_)}},
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddIconRsp, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AddIconRsp, _impl_.error_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(AddIconRsp, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string url = 2;
    {PROTOBUF_FIELD_OFFSET(AddIconRsp, _impl_.url_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\3\0\0\0\0\0"
    "message.AddIconRsp"
    "url"
  }},
};

::uint8_t* AddIconRsp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.AddIconRsp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_error(), target);
  }

  // string url = 2;
  if (!this->_internal_url().empty()) {
    const std::string& _s = this->_internal_url();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.AddIconRsp.url");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.AddIconRsp)
  return target;
}

::size_t AddIconRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.AddIconRsp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string url = 2;
  if (!this->_internal_url().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_url());
  }

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AddIconRsp::_class_data_ = {
    AddIconRsp::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AddIconRsp::GetClassData() const {
  return &_class_data_;
}

void AddIconRsp::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AddIconRsp*>(&to_msg);
  auto& from = static_cast<const AddIconRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.AddIconRsp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_url().empty()) {
    _this->_internal_set_url(from._internal_url());
  }
  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddIconRsp::CopyFrom(const AddIconRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.AddIconRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AddIconRsp::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* AddIconRsp::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AddIconRsp::InternalSwap(AddIconRsp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.url_, &other->_impl_.url_, arena);
        swap(_impl_.error_, other->_impl_.error_);
}

::google::protobuf::Metadata AddIconRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[7]);
}
// ===================================================================

class GetIconReq::_Internal {
 public:
};

GetIconReq::GetIconReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.GetIconReq)
}
inline PROTOBUF_NDEBUG_INLINE GetIconReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : url_(arena, from.url_),
        _cached_size_{0} {}

GetIconReq::GetIconReq(
    ::google::protobuf::Arena* arena,
    const GetIconReq& from)
    : ::google::protobuf::Message(arena) {
  GetIconReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:message.GetIconReq)
}
inline PROTOBUF_NDEBUG_INLINE GetIconReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : url_(arena),
        _cached_size_{0} {}

inline void GetIconReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetIconReq::~GetIconReq() {
  // @@protoc_insertion_point(destructor:message.GetIconReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetIconReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.url_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GetIconReq::Clear() {
// @@protoc_insertion_point(message_clear_start:message.GetIconReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.url_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GetIconReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2> GetIconReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetIconReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string url = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetIconReq, _impl_.url_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string url = 1;
    {PROTOBUF_FIELD_OFFSET(GetIconReq, _impl_.url_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\3\0\0\0\0\0\0"
    "message.GetIconReq"
    "url"
  }},
};

::uint8_t* GetIconReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.GetIconReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string url = 1;
  if (!this->_internal_url().empty()) {
    const std::string& _s = this->_internal_url();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "message.GetIconReq.url");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.GetIconReq)
  return target;
}

::size_t GetIconReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.GetIconReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string url = 1;
  if (!this->_internal_url().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_url());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GetIconReq::_class_data_ = {
    GetIconReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GetIconReq::GetClassData() const {
  return &_class_data_;
}

void GetIconReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GetIconReq*>(&to_msg);
  auto& from = static_cast<const GetIconReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.GetIconReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_url().empty()) {
    _this->_internal_set_url(from._internal_url());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetIconReq::CopyFrom(const GetIconReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.GetIconReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GetIconReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GetIconReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GetIconReq::InternalSwap(GetIconReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.url_, &other->_impl_.url_, arena);
}

::google::protobuf::Metadata GetIconReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[8]);
}
// ===================================================================

class GetIconRsp::_Internal {
 public:
};

GetIconRsp::GetIconRsp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:message.GetIconRsp)
}
inline PROTOBUF_NDEBUG_INLINE GetIconRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : icon_pixmap_(arena, from.icon_pixmap_),
        _cached_size_{0} {}

GetIconRsp::GetIconRsp(
    ::google::protobuf::Arena* arena,
    const GetIconRsp& from)
    : ::google::protobuf::Message(arena) {
  GetIconRsp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.error_ = from._impl_.error_;

  // @@protoc_insertion_point(copy_constructor:message.GetIconRsp)
}
inline PROTOBUF_NDEBUG_INLINE GetIconRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : icon_pixmap_(arena),
        _cached_size_{0} {}

inline void GetIconRsp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_ = {};
}
GetIconRsp::~GetIconRsp() {
  // @@protoc_insertion_point(destructor:message.GetIconRsp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetIconRsp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.icon_pixmap_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GetIconRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:message.GetIconRsp)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.icon_pixmap_.ClearToEmpty();
  _impl_.error_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GetIconRsp::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> GetIconRsp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetIconRsp_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes icon_pixmap = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GetIconRsp, _impl_.icon_pixmap_)}},
    // int32 error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetIconRsp, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetIconRsp, _impl_.error_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 error = 1;
    {PROTOBUF_FIELD_OFFSET(GetIconRsp, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bytes icon_pixmap = 2;
    {PROTOBUF_FIELD_OFFSET(GetIconRsp, _impl_.icon_pixmap_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* GetIconRsp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.GetIconRsp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_error(), target);
  }

  // bytes icon_pixmap = 2;
  if (!this->_internal_icon_pixmap().empty()) {
    const std::string& _s = this->_internal_icon_pixmap();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.GetIconRsp)
  return target;
}

::size_t GetIconRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.GetIconRsp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes icon_pixmap = 2;
  if (!this->_internal_icon_pixmap().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_icon_pixmap());
  }

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GetIconRsp::_class_data_ = {
    GetIconRsp::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GetIconRsp::GetClassData() const {
  return &_class_data_;
}

void GetIconRsp::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GetIconRsp*>(&to_msg);
  auto& from = static_cast<const GetIconRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:message.GetIconRsp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_icon_pixmap().empty()) {
    _this->_internal_set_icon_pixmap(from._internal_icon_pixmap());
  }
  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetIconRsp::CopyFrom(const GetIconRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.GetIconRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GetIconRsp::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GetIconRsp::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GetIconRsp::InternalSwap(GetIconRsp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.icon_pixmap_, &other->_impl_.icon_pixmap_, arena);
        swap(_impl_.error_, other->_impl_.error_);
}

::google::protobuf::Metadata GetIconRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_message_2eproto_getter, &descriptor_table_message_2eproto_once,
      file_level_metadata_message_2eproto[9]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace message
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
